### ISSUE TITLE
可否加点注解，比如$和_是什么含义？

### ISSUE THREAD

**Issue by wenzi0github** [yafoo/jj.js#1]
比如：

https://github.com/yafoo/jj.js/blob/2290f5ad83ce6685faacb644fb440e161370d84e/lib/ctx.js#L10

$ 是什么？
_ 又是什么意思？

**Comment by yafoo** [comment]
嗯，系统文档还需要完善。

这个文件是系统模块实现自动加载的核心，原理是在控制器、模型中使用this调用包含$前缀的属性或方法时，做判断并加载。实际开发时，用不到这个文件，能用的主要是继承控制器类、模型类、中间件类，还有就是可以直接调用数据库类。

暂时可以参考我用这个框架开发的博客程序[melog](https://github.com/yafoo/melog)
